// Vince Petrelli All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace LOP_GameplayTags
{
	//Input Tags
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_DashAndRun);

	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack);

	//Player Tags
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_DashAndRun);


	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpFinisher);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Dash);

	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	//Enemy Tags
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	//Shared Tags
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);

	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	LISEOFP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
}

